apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-spring-app  #Your app's name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react-spring-app
    spec:
      volumes:
        - name: spanner-creds
          secret:
            secretName: springboot-api-secret
      containers:
      - name: react-spring-app  #Your app will be the running container you built
        image: gcr.io/named-deck-252519/my-spring-api:v1
        ports:
          - containerPort: 8080
            name: app
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/app-secrets/google-secret.json
        volumeMounts:
          - name: spanner-creds
            mountPath: /secrets/app-secrets
            readOnly: true
    
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: react-spring-app  #This will be the name of your load balancer
#  namespace: default
#spec:
#  selector:
#    app: react-spring-app  #The load balancer will be attached to the app you specify by name here
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 8080
#  type: LoadBalancer
#  loadBalancerSourceRanges:  #Firewall rules
#    - 151.140.0.0/16
#    - 165.130.0.0/16
#    - 207.11.0.0/17
#    - 50.207.27.182/32
#    - 98.6.11.8/29